language: node_js
node_js: 7

before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
  
script:
  - ./test.sh

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
